FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/usr/local sh
ENTRYPOINT ["flyctl"]
